///////////////////////////////////////////////////////////
//  Player.cs
//  Implementation of the Class Player
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

using System;

namespace Mazegame.Entity
{
    public class Player : Character
    {
        private Location currentLocation;
        private Inventory inventory = new Inventory();

        public Player()
        {
        }

        public Player(String name)
            : base(name)
        {
            inventory.AddMoney(20);
        }

        public Location CurrentLocation
        {
            get { return currentLocation; }
            set { currentLocation = value; }
        }

        public Inventory Inventory
        {
            get { return inventory; }
            set { inventory = value; }
        }
    }
}
//end namespace Entity